export interface Filters {
    cat2 : any, 
    cat3: any,
    cat4: any,
    location: any, 
    engine: any,
    unit: any,
    F_debriefDate: any,
    T_debriefDate: any,
    T_TotalCost: any,
    F_TotalCost: any,
    T_FinishWeight: any,
    F_FinishWeight: any,
    FinishWeight_KG: 1,
    PartNumber: any,
    PartName: any,
    ProgramName: any,
    like: any,
}
