export interface suppliercost {
    tcoid:number,
    tcO_Number:number,
    tcO_Version:number,
    modelmartId: string,
    supplier_Number:string,
    supplier_Company: string,
    supplier_CountryOfOrigin: string,
    debriefDate:string,
    cummins_Date:string,
    pbPerPiece_Material: number,
    pbPerPiece_PurchasedParts: number,
    pbPerPiece_OutsourcedpartParts:number,
    pbPerPiece_LabourCostPerPiece:number,
    pbPerPiece_OHCostPerPiece:number,
    pbPerPiece_SurfaceTreatments:number,
    pbPerPiece_SGA: number,
    pbPerPiece_Profit: number,
    sP_FreightLogisticsCost:number,
    pbPerPiece_PackLogisticsWare:number,
    pbPerPiece_TotalPartPrice:number,
    supplier_ExchangeRateToUSD:number,
    forex:number,
    mfgRegion:number
}